#ifndef MRS_LIB_INTERNAL_VERSION_MACROS_HPP_
#define MRS_LIB_INTERNAL_VERSION_MACROS_HPP_

#define MRS_LIB_INTERNAL_DEFAULT_API_VERSION 1

#ifndef MRS_LIB_API_VERSION
#define MRS_LIB_API_VERSION MRS_LIB_INTERNAL_DEFAULT_API_VERSION
#endif

#define MRS_LIB_INTERNAL_INLINE_API_V1
#define MRS_LIB_INTERNAL_INLINE_API_V2

#if MRS_LIB_API_VERSION == 1
#undef MRS_LIB_INTERNAL_INLINE_API_V1
#define MRS_LIB_INTERNAL_INLINE_API_V1 inline
#else
#error "Unsupported value for MRS_LIB_API_VERSION"
#endif


#endif // MRS_LIB_INTERNAL_VERSION_MACROS_HPP_
