name: nix_package_build

on:

  push:
    branches: [ nix ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/nix_package_build.yml@nix
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      CACHIX: ${{ secrets.CACHIX }}
