name: rostest

on:

  push:
    branches: [ ros2_devel ]

    paths-ignore:
      - '**/README.md'

  pull_request:
    branches: [ ros2 ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/rostest.yml@ros2
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
